version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jx4zz6dxk4tx"
s3_prefix = "test-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
