AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Amazon API Gateway to AWS Lambda to Amazon DynamoDB

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Timeout: 3

#Description:
  #String

#Metadata:
  #template metadata

#Parameters:
  #set of parameters

#Mappings:
  #set of mappings

#Conditions:
  #set of conditions

Resources:
  LambdaFunctionName:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Description: 'Lambda function inserts data into DynamoDB table'
    Properties:
      FunctionName: SiteCounter
      Handler: index.lambda_handler
      Runtime: python3
      CodeUri: src/

      Policies: #Need to see how to connect this
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable

      Events:
        ApiEventName:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitor_count
            Method: GET
            

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SiteCounter


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor_count/"
  LambdaFunctionName:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt LambdaFunctionName.Arn
#  VisitorCountFunctionIamRole:
#    Description: "Implicit IAM Role created for Visitor Count function"
#    Value: !GetAtt VisitorCountFunctionRole.Arn
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
